pipeline {
    // 请确保agent上配置了
    // 1. npm
    // 2. angular cli
    // 3. git
    agent{
        label 'building'

    parameters {
        string(name:'BRANCH', defaultValue: 'dev', description: 'which branch to build?')
        string(name:'BACKEND_URL', defaultValue: 'http://beta.flyingjack.top:8081/', description: 'Input the backend url')
    }

    options {
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        TZ = 'Asia/Shanghai'
    }

    stages {
        stage('Preparation'){
            steps {
                git branch: "${params.BRANCH}", credentialsId: 'gitee', url: 'git@gitee.com:zuminli/wms_frontend.git'
            }
        }

        stage('Build') {
            steps {
                echo '开始安装依赖'
                sh "npm install"
                echo '依赖完成'
                echo '开始安装依赖'

                echo '设置后端地址'
                sh "sed -i 's/https://api.flyingjack.top/${params.BACKEND_URL}/' src/environments/environment.prod.ts"
                sh 'cat src/environments/environment.prod.ts'
                echo '后端地址设置完成'

                echo '开始构建'
                sh "ng build --configuration=production"
            }
        }
    }

    post {
        always {
            cleanWs cleanWhenFailure: false, cleanWhenNotBuilt: false, cleanWhenUnstable: false
        }
    }
}
